import {useState} from 'react'
import {Link,useNavigate,useSearch} from '@tanstack/react-router'
import {ArrowRight,LockKeyhole} from 'lucide-react'
import {Button,Card,Input} from '../components/ui'
import {useAuth} from '../auth/context'

export function LoginPage(){
 const {login}=useAuth(); const nav=useNavigate(); const search=useSearch({from:'/login'}) as {redirect:string}; const [email,setEmail]=useState('collector@nova.test'); const [password,setPassword]=useState('nova123'); const [error,setError]=useState('')
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{await login(email,password);nav({to:search.redirect||'/'})}catch{setError('Não foi possível entrar. Use collector@nova.test / nova123.')}}
 return <AuthShell title="SEJA DONO DO FUTURO DA ARTE DIGITAL" subtitle="Entre na sua conta para continuar sua coleção."><form onSubmit={submit} className="space-y-4"><label className="block text-[10px] text-[#b8947f]">E-mail<Input value={email} onChange={e=>setEmail(e.target.value)} type="email" required className="mt-2"/></label><label className="block text-[10px] text-[#b8947f]">Senha<Input value={password} onChange={e=>setPassword(e.target.value)} type="password" required className="mt-2"/></label>{error&&<p className="border border-[#68401f] bg-[#3d2516] p-3 text-[9px] text-[#e1a06a]">{error}</p>}<Button className="w-full rounded-[2px]" size="lg">Entrar <ArrowRight size={14}/></Button></form><p className="mt-5 text-center text-[9px] text-[#745a4b]">Ainda não tem conta? <Link to="/register" className="text-[#dd9550]">Criar conta</Link></p></AuthShell>
}

function AuthShell({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="relative mx-auto min-h-[calc(100vh-120px)] max-w-[1180px] px-4 py-10 sm:px-6"><div className="grid overflow-hidden border border-[#3b2116] bg-[#160d0a] lg:grid-cols-[1.18fr_.82fr]"><div className="relative hidden min-h-[560px] lg:block"><img src="/assets/emerald-ape.png" alt="Arte Emerald Ape" className="absolute inset-0 h-full w-full object-cover opacity-70"/><div className="absolute inset-0 bg-gradient-to-r from-[#160d0a]/50 to-[#160d0a]"/><div className="absolute left-8 top-10 max-w-md"><div className="text-[9px] uppercase tracking-[.2em] text-[#cc7d3b]">Future Ape Collection</div><h2 className="mt-4 text-4xl font-semibold leading-none text-[#f2e5d9]">SEJA DONO DO FUTURO<br/>DA ARTE DIGITAL</h2></div></div><Card className="relative rounded-none border-0 bg-[#1b100c] p-8 sm:p-10 lg:min-h-[560px] lg:border-l lg:border-[#3b2116]"><div className="mb-8 flex items-center gap-2"><span className="grid h-8 w-8 place-items-center border border-[#9b5c2b] text-[11px] font-bold text-[#dc9450]">N</span><span className="text-[11px] font-semibold tracking-[.3em] text-[#ddcaba]">NOVA</span></div><div className="flex items-center gap-2 text-[9px] text-[#75594b]"><LockKeyhole size={12}/> Conta de colecionador</div><h1 className="mt-4 text-2xl font-semibold text-[#eee0d4]">{title}</h1><p className="mt-2 text-[10px] leading-5 text-[#785e50]">{subtitle}</p><div className="mt-7">{children}</div></Card></div></div>}
