import {Link,useParams} from '@tanstack/react-router'
import {CheckCircle2, Clock3, XCircle, ArrowRight, RefreshCw} from 'lucide-react'
import {useOrder,useOrderDecision} from '../api/hooks'
import {eth} from '../lib/format'
import {Button,Card,EmptyState,Skeleton} from '../components/ui'

export function OrderPage(){
  const {id}=useParams({from:'/order/$id'}); const {data:order,isLoading}=useOrder(id); const decision=useOrderDecision()
  if(isLoading)return <div className="mx-auto max-w-[620px] px-4 py-16"><Skeleton className="h-[440px]"/></div>
  if(!order)return <div className="mx-auto max-w-[620px] px-4 py-16"><EmptyState title="Pedido não encontrado" description="Não foi possível recuperar o snapshot deste pedido."/></div>
  if(order.status==='pending')return <div className="mx-auto max-w-[620px] px-4 pb-16 pt-12"><Card className="overflow-hidden rounded-[2px]"><div className="bg-[#24140e] p-7 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[#4d2c19] text-[#e39a53]"><Clock3/></div><h1 className="mt-5 text-2xl font-semibold text-[#f0e1d5]">Pedido em processamento</h1><p className="mx-auto mt-2 max-w-md text-[10px] leading-5 text-[#765b4c]">A compra foi criada e aguarda a decisão da carteira simulada. Você pode atualizar a página sem criar outro pedido.</p></div><div className="grid gap-2 p-5 sm:grid-cols-2"><Button variant="outline" className="rounded-[2px]" onClick={()=>decision.mutate({id,accept:false})}><XCircle size={14}/>Recusar pagamento</Button><Button className="rounded-[2px]" onClick={()=>decision.mutate({id,accept:true})}><CheckCircle2 size={14}/>Confirmar pagamento</Button></div></Card></div>
  const confirmed=order.status==='confirmed'
  return <div className="mx-auto max-w-[620px] px-4 pb-16 pt-12"><Card className="overflow-hidden rounded-[2px]"><div className="bg-[#24140e] p-7 text-center"><div className={`mx-auto grid h-14 w-14 place-items-center rounded-full ${confirmed?'bg-[#25402f] text-[#9bd5ad]':'bg-[#48241f] text-[#dc8e7e]'}`}>{confirmed?<CheckCircle2/>:<XCircle/>}</div><h1 className="mt-5 text-2xl font-semibold text-[#f0e1d5]">{confirmed?'Confirmação de Pedido':'Pagamento recusado'}</h1><p className="mx-auto mt-2 max-w-md text-[10px] leading-5 text-[#765b4c]">{confirmed?'Seu recibo reproduz o snapshot do pedido no momento da compra.':'O pagamento foi recusado na simulação. Os itens continuam preservados para você.'}</p></div><div className="p-5"><div className="grid grid-cols-2 gap-2 sm:grid-cols-3"><Info label="Pedido" value={order.id}/><Info label="Transação" value={order.transactionId}/><Info label="Total" value={eth(order.total)}/><Info label="Subtotal" value={eth(order.subtotal)}/><Info label="Taxa de rede" value={eth(order.networkFee)}/><Info label="Criado em" value={new Date(order.createdAt).toLocaleString('pt-BR')}/></div><div className="mt-5 space-y-2">{order.items.map(item=><div key={item.nftId} className="flex items-center gap-3 border border-[#3b2116] bg-[#160c09] p-2"><img src={item.image} alt={item.name} className="h-11 w-11 object-cover"/><div className="min-w-0 flex-1"><div className="truncate text-[10px] font-semibold text-[#d9c7b9]">{item.name}</div><div className="mt-1 text-[8px] text-[#72594a]">Qtd {item.quantity} · {eth(item.unitPrice)}</div></div><div className="text-[9px] text-[#d7924e]">{eth(item.lineTotal)}</div></div>)}</div><div className="mt-5 flex gap-2"><Button asChild className="rounded-[2px]"><Link to="/">Continuar explorando <ArrowRight size={13}/></Link></Button>{!confirmed&&<Button variant="outline" className="rounded-[2px]" onClick={()=>decision.mutate({id,accept:true})}><RefreshCw size={13}/>Tentar novamente</Button>}</div></div></Card></div>
}
function Info({label,value}:{label:string;value:string}){return <div className="border border-[#3b2116] bg-[#160c09] p-3"><div className="text-[7px] uppercase tracking-[.16em] text-[#6f5447]">{label}</div><div className="mt-1 break-all text-[9px] text-[#bfa493]">{value}</div></div>}
