import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {api} from './client'
import type {Cart,NFT,Order,Quote,User,Wallet} from '../types'
import {addGuestCartItem} from '../cart/guest'
export const keys={session:['session'],nfts:['nfts'],nft:(id:string)=>['nft',id],cart:['cart'],favorites:['favorites'],profile:['profile'],wallets:['wallets'],orders:['orders'],order:(id:string)=>['order',id]}
export function useSession(){const enabled=Boolean(localStorage.getItem('nova.token'));return useQuery({queryKey:keys.session,queryFn:async()=>((await api.get('/session')).data.user as User),enabled,retry:false,staleTime:30_000})}
export function useNfts(params:Record<string,string|number>){return useQuery({queryKey:[...keys.nfts,params],queryFn:async()=>((await api.get('/nfts',{params})).data as {items:NFT[];page:number;size:number;total:number;pages:number}),placeholderData:(prev)=>prev,staleTime:15_000})}
export function useNft(id:string){return useQuery({queryKey:keys.nft(id),queryFn:async()=>((await api.get(`/nfts/${id}`)).data.nft as NFT),retry:false,refetchInterval:import.meta.env.VITE_E2E==='true'?1000:false})}
export function useCart(enabled=true){return useQuery({queryKey:keys.cart,queryFn:async()=>((await api.get('/cart')).data as {cart:Cart;quote:Quote}),enabled,refetchInterval:20_000})}
export function useFavorites(enabled=true){return useQuery({queryKey:keys.favorites,queryFn:async()=>((await api.get('/favorites')).data.ids as string[]),enabled})}
export function useAddCart(){const qc=useQueryClient();return useMutation({mutationFn:async({nftId,quantity}:{nftId:string;quantity:number})=>{if(!localStorage.getItem('nova.token')){addGuestCartItem(nftId,quantity);return {data:{guest:true}}};return api.post('/cart/items',{nftId,quantity})},onSuccess:(r)=>{if(r.data?.guest)return;qc.setQueryData(keys.cart,r.data)}})}
export function useCartQuantity(){const qc=useQueryClient();return useMutation({mutationFn:({id,quantity}:{id:string;quantity:number})=>api.patch(`/cart/items/${id}`,{quantity}),onSuccess:(r)=>qc.setQueryData(keys.cart,r.data)})}
export function useRemoveCart(){const qc=useQueryClient();return useMutation({mutationFn:(id:string)=>api.delete(`/cart/items/${id}`),onSuccess:(r)=>qc.setQueryData(keys.cart,r.data)})}
export function useCoupon(){const qc=useQueryClient();return useMutation({mutationFn:(code:string)=>api.post('/cart/coupon',{code}),onSuccess:(r)=>qc.setQueryData(keys.cart,r.data)})}
export function useRemoveCoupon(){const qc=useQueryClient();return useMutation({mutationFn:()=>api.delete('/cart/coupon'),onSuccess:(r)=>qc.setQueryData(keys.cart,r.data)})}
export function useToggleFavorite(){const qc=useQueryClient();return useMutation({mutationFn:({id,favorite}:{id:string;favorite:boolean})=>favorite?api.post(`/favorites/${id}`):api.delete(`/favorites/${id}`),onMutate:async({id,favorite})=>{await qc.cancelQueries({queryKey:keys.favorites});const prev=qc.getQueryData<string[]>(keys.favorites)??[];qc.setQueryData(keys.favorites,favorite?[...prev,id]:prev.filter(x=>x!==id));return{prev}},onError:(_e,_v,ctx)=>ctx&&qc.setQueryData(keys.favorites,ctx.prev),onSettled:()=>qc.invalidateQueries({queryKey:keys.favorites})})}
export function useOrders(){return useQuery({queryKey:keys.orders,queryFn:async()=>((await api.get('/orders')).data.orders as Order[]),staleTime:5_000})}
export function useOrder(id:string){return useQuery({queryKey:keys.order(id),queryFn:async()=>((await api.get(`/orders/${id}`)).data.order as Order),refetchInterval:3000})}
export function useCreateOrder(){const qc=useQueryClient();return useMutation({mutationFn:({quoteVersion,key}:{quoteVersion:string;key:string})=>api.post('/orders',{quoteVersion},{headers:{'Idempotency-Key':key}}),onSuccess:(r)=>{qc.setQueryData(keys.order(r.data.order.id),r.data.order);qc.invalidateQueries({queryKey:keys.orders});qc.invalidateQueries({queryKey:keys.cart})}})}
export function useOrderDecision(){const qc=useQueryClient();return useMutation({mutationFn:({id,accept}:{id:string;accept:boolean})=>api.post(`/orders/${id}/decision`,{accept}),onSuccess:(r)=>{qc.setQueryData(keys.order(r.data.order.id),r.data.order);qc.invalidateQueries({queryKey:keys.orders});qc.invalidateQueries({queryKey:keys.cart})}})}
export function useProfile(){return useQuery({queryKey:keys.profile,queryFn:async()=>((await api.get('/profile')).data.user as User)})}
export function useUpdateProfile(){const qc=useQueryClient();return useMutation({mutationFn:(body:Partial<Pick<User,'name'|'avatar'>>)=>api.patch('/profile',body),onSuccess:(r)=>qc.setQueryData(keys.profile,r.data.user)})}
export function useChangePassword(){return useMutation({mutationFn:(body:{currentPassword:string;newPassword:string})=>api.patch('/profile/password',body)})}
export function useWallets(){return useQuery({queryKey:keys.wallets,queryFn:async()=>((await api.get('/wallets')).data.wallets as Wallet[])})}
export function useSaveWallet(){const qc=useQueryClient();return useMutation({mutationFn:(body:Partial<Wallet> & {id?:string})=>body.id?api.patch(`/wallets/${body.id}`,body):api.post('/wallets',body),onSuccess:(r)=>qc.setQueryData(keys.wallets,r.data.wallets)})}
